<script setup>
import { onMounted, reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import api,{clearAuth} from '../api';
const router=useRouter(),store=ref(null),status=reactive({open_status:'open',queue_minutes:0,seats_available:0}),deal=reactive({title:'',price:99,stock:20}),err=ref('');
async function load(){try{store.value=await api.merchantStore();status.open_status=store.value.live_open_status;status.queue_minutes=store.value.live_queue_minutes;status.seats_available=store.value.live_seats_available}catch(e){err.value=e.message}}
async function save(){try{store.value=await api.merchantStatus({...status})}catch(e){err.value=e.message}}
async function publish(){try{await api.merchantDeal({...deal});await load()}catch(e){err.value=e.message}}
function logout(){clearAuth();router.replace('/login')} onMounted(load);
</script>
<template><div class="workspace"><header><div><small>MERCHANT WORKSPACE</small><h1>{{store?.name||'店铺运营'}}</h1><p>{{store?.floor}}F · {{store?.business_hours}} · 负责人 {{store?.manager_name}}</p></div><button @click="logout">退出</button></header><p v-if="err" class="err">{{err}}</p><section class="card"><h2>实时营业状态</h2><div class="grid"><label>状态<select v-model="status.open_status"><option value="open">正常营业</option><option value="busy">客流繁忙</option><option value="closed">暂停营业</option></select></label><label>排队分钟<input v-model.number="status.queue_minutes" type="number"/></label><label>可用座位<input v-model.number="status.seats_available" type="number"/></label></div><button class="primary" @click="save">同步给游客端</button></section><section class="card"><h2>发布优惠</h2><div class="grid"><label>优惠标题<input v-model="deal.title"/></label><label>价格<input v-model.number="deal.price" type="number"/></label><label>库存<input v-model.number="deal.stock" type="number"/></label></div><button class="primary" @click="publish">发布优惠</button><div v-for="d in store?.deals||[]" :key="d.id" class="row"><span>{{d.title}}</span><b>¥{{d.price}} · {{d.stock}}份</b></div></section></div></template>
<style scoped>.workspace{min-height:100%;background:#f4f6fb;padding:28px}header{display:flex;justify-content:space-between;background:linear-gradient(135deg,#064e3b,#059669);color:#fff;border-radius:22px;padding:28px}header h1{margin:7px 0}header small{letter-spacing:2px;color:#a7f3d0}header button{align-self:flex-start;background:#ffffff22;color:#fff;border:0;border-radius:20px;padding:8px 14px}.card{max-width:none}.grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:14px}label{font-size:13px;color:#6b7280}input,select{display:block;width:100%;margin-top:7px;padding:12px;border:1px solid #e5e7eb;border-radius:10px}.primary{margin-top:18px;border:0;border-radius:24px;padding:12px 22px;background:#059669;color:#fff}.row{display:flex;justify-content:space-between;padding:14px 0;border-bottom:1px solid #e5e7eb}.err{color:#ef4444}</style>
